### ISSUE TITLE
Memory leak with stream pipe

### ISSUE THREAD

**Issue by dirkritters** [mhart/kinesis#13]
Hello,

first of all thanks for the great script - it makes getting data from kinesis via node.js so much easier as the aws sdk does. I am using a very basic script for testing without doing anything with the received records right now:

var kinesis 	= require('kinesis'),
    Transform 	= require('stream').Transform,
    accessKey	= "xxx",
    secretKey	= "xxx";
require('https').globalAgent.maxSockets = Infinity;
var bufferify = new Transform({objectMode: true})
bufferify._transform = function(record, encoding, cb) {
cb();
}
var kinesisStream = kinesis.stream({cacheSize:100, region: 'eu-west-1', credentials: {accessKeyId: accessKey, secretAccessKey: secretKey}, name: 'xxx', oldest: false});
kinesisStream.pipe(bufferify);

After a few hours, the process runs out of memory and the script stucks. I am using an EC2 m3.medium with 3,75 GB Ram. Is there some problem in the concept between node.js streams and kinesis?

Would be really happy, if you could help with this!

**Comment by mhart** [comment]
Not sure off the top of my head. Which Node.js version?

The Transform stream doesn't actually pass through any data – I'm not sure if that makes a difference or not, but have you tried piping to a stream that actually consumes the data, like stdout, instead?

**Comment by mhart** [comment]
Actually, it may just be Node.js holding on to the socket listeners (and not garbage collecting them).

What happens if you use something that's not infinite for `maxSockets`:

```js
require('https').globalAgent.maxSockets = 1024
```

**Comment by mhart** [comment]
Have just run this for four hours now on a stream with one shard, Node.js v0.10.36 on Mac OS X and haven't seen the process climb higher than 210MB. The heap size is 26.6MB, largely made up of `addListener` closures from Node.js' `Socket`.

If I use `1024` instead of `Infinity` for `maxSockets`, there's even less heap used (16.3MB)

So I'm unable to reproduce this unfortunately.

**Comment by dirkritters** [comment]
Thanks a lot for your response. I've tried with the 1024 for max https connections - it works much more stable right now.
