### ISSUE TITLE
How do you do a simple write?

### ISSUE THREAD

**Issue by justinmchase** [mhart/kinesis#21]
I am just testing my stream and lambda function, I want to write some dummy data. I'm doing this:

```
var kinesis = require('kinesis')
var testing = kinesis.stream('testing')
testing.write('hello kinesis!')
testing.on('finish', () => {
	console.log('done sending...')
})
```

But get this error:
```
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
```

**Comment by mhart** [comment]
Kinesis uses binary data. Try `testing.write(new Buffer('hello kinesis!'))`

I should probably check for people trying to write strings directly and either convert to Buffers or error

**Comment by mhart** [comment]
@justinmchase how'd you go with this?

**Comment by justinmchase** [comment]
I haven't tried it yet to be honest. I just found out that I can press the Test button in aws console and it crams a record into the function for testing. I will eventually give this a try though. I'll close it for now, thanks!
