### ISSUE TITLE
UnknownOperationException after trying to send data

### ISSUE THREAD

**Issue by alowenst** [mhart/kinesis#22]
Hi!,

I'm trying to send data to an existing stream and I'm getting. 
```
{ [UnknownOperationException: {"__type":"UnknownOperationException"}]
statusCode: 400,
name: 'UnknownOperationException',
message: '{"__type":"UnknownOperationException"}' }
```

There's not much information about the available operations. I assume that putRecord should be used based on a couple of issues submitted.
This is my code
```
kinesis.request('putRecord',
    {
        "a":"aa",
        "b":"bb",
        "c":[
            {
                "d":"dd",
        ]},
    {StreamName: 'streamName'}, function(err) {

    if (err) {
        console.log(err);
    }
});
```
What am I doing wrong?

Thanks.

**Comment by mhart** [comment]
The action name is `PutRecord`: http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecord.html

(note the capital `P`)

**Comment by alowenst** [comment]
Thanks!
