### ISSUE TITLE
Integration with kinesalite

### ISSUE THREAD

**Issue by cantide5ga** [mhart/kinesis#24]
Recommendation on setting endpoint (host:port) and credentials in `options` to use a local kinesalite?  This is a follow-up to mhart/kinesalite#39

For local integration tests event sourcing to a lambda function.  Would this project emulate similar to KCL?  I'm trying to avoid the DynamoDB issue discussed in mhart/kinesalite#11

Sorry for dragging in a separate repo into the discussion; just wanted to provide context.

**Comment by RodH257** [comment]
This is from the kinesalite readme: 
```
Or with the kinesis module (currently only works in https mode, when kinesalite is started with --ssl):

var kinesis = require('kinesis')

kinesis.listStreams({host: 'localhost', port: 4567}, console.log)
```

Unfortunate that it only works with SSL version though

**Comment by cantide5ga** [comment]
Not sure if I went this route yet, but will give it a go here in a bit and follow-up by midday.  Thanks @RodH257!

**Comment by cantide5ga** [comment]
Great - got this working but question remains how to invoke a lambda function (on local) emulating the KCL.  This all based on the assumption that my use case is common (if not, interested to know what folks are using these two projects for) - just not finding a lot of examples on making the integration realistic compared to AWS.

**Comment by cantide5ga** [comment]
Not really getting anything practical out of this and will need to sideline it for now.  Will close to reduce noise and circle back in the near future.
