### ISSUE TITLE
Running on AWS Fargate

### ISSUE THREAD

**Issue by valkko** [mhart/kinesis#27]
Hi,

I have a project that's been running fine with kinesis in docker, through ECS & EC2. Now I'm trying to see if we can run the project on AWS Fargate instead of the traditional EC2. However, the kineses connection seems to fail in there with EINVAL, it's still running fine locally and on EC2, with the environment being otherwise the same (same node versions etc).

The error I'm getting is:

Node 9.7.1:
```
events.js:112
throw er; // Unhandled 'error' event
^
Error: connect EINVAL 169.254.169.254:80 - Local (0.0.0.0:0)
at internalConnect (net.js:956:16)
at defaultTriggerAsyncIdScope (internal/async_hooks.js:281:19)
at net.js:1058:9
at process._tickCallback (internal/process/next_tick.js:112:11)
error An unexpected error occurred: "Command failed.
Exit code: 1
```

Node 8.9.4:
```
events.js:183
throw er; // Unhandled 'error' event
^
Error: connect EINVAL 169.254.169.254:80 - Local (0.0.0.0:0)
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at internalConnect (net.js:971:16)
at net.js:1065:9
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
error Command failed with exit code 1.
```

The problem most likely isn't with this library, but any ideas if that can be worked around?

**Comment by justingreenberg** [comment]
hi @valkko I am having the same issue—were you able to solve this?

**Comment by valkko** [comment]
Nope, ended up switching to EC2 with the service using this.

**Comment by isaacdre** [comment]
Looks like your fargate container was attempting to connect to another service outside the VPC? You might have to open outbound traffic ports to allow that. / adjust your service rolls accordingly.

(Rough guess for anyone else hitting this issue)

**Comment by d4nyll** [comment]
@isaacdre `169.254.169.254` is the link-local address for EC2 metadata service, so it should be reachable from any EC2 instances.

The `EINVAL` error code indicates that the metadata service received invalid parameters.
