### ISSUE TITLE
Closing/Deleting a Kinesis Stream

### ISSUE THREAD

**Issue by chody-h** [mhart/kinesis#28]
The [AWS API](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_DeleteStream.html) specifies you should call 'DeleteStream'. However, I tried using this library to delete a stream using the `.request` function, but I couldn't get it to work (I was also using Kinesalite):

```
kinesis.request("DeleteStream", {StreamName: name}, { host: "localhost", port: 4567 }, (err) => {
    if (err) console.log(`Stream ${name} could not be deleted: ${err}`);
    console.log(`Stream ${name} deleted.`);
`});
```

It ends up silently failing somewhere in the aws cred call (line 327 of index.js). My callback function I provided was never called (nothing prints to console). I confirmed that I was able to create streams using the same method so I'm not sure what the problem could be. Any ideas?

**Comment by mhart** [comment]
I notice you're making a call to a local kinesis instance – try passing a dummy region and credentials in to the request call, so that the credentials aren't trying to be loaded. The relevant code that would try to do this is here: https://github.com/mhart/kinesis/blob/master/index.js#L272-L273

So try `{ host: "localhost", port: 4567, region: "us-east-1", credentials: {accessKeyId: "a", secretAccessKey: "a"} }`

**Comment by chody-h** [comment]
Great suggestion - adding those attributes got me past the AWS cred call. However, my callback function is still not executing. I managed to trace the call around and it seems like the [https.request callback function](https://github.com/mhart/kinesis/blob/master/index.js#L331-L356) isn't executing. I confirmed it executes with the other calls like create and list streams.

I put a few log statements in the kinesalite server, and it appears to never receive the deleteStream request.

**Comment by chody-h** [comment]
Found my problem: I was checking too quickly to see if the stream was deleted. Was able to successfully delete a stream with the suggestion above by doing one or both of the following:
- give kinesis time to delete the stream before checking the delete occurred (I was listing the streams)
- set the `deleteStreamMs` parameter in the kinesaLite server
