### ISSUE TITLE
you need to transform bunyan output to a buffer to use kinesis

### ISSUE THREAD

**Issue by twhid** [mhart/kinesis#30]
Greetings,

Using node v12.14.0

I'm using this module with bunyan and it does not work as expected. (There's a chance I'm doing something wrong, please excuse me if so.)

```js
const kinesisSink = kinesis.stream({ name: 'my-name', region: 'us-east-1' });
const logger = bunyan.createLogger({ name: 'logger-name' });

logger.addStream({
    name: 'kinesis',
    stream: kinesisSink,
    level: 'info',
});
```

Trying to use this module in that manner above, results in an error: 
```
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
```

And AWS also reports a `SerializationException: {"__type":"SerializationException"}`. 

I believe this is because the [`_write` method](https://github.com/mhart/kinesis/blob/master/index.js#L177) is getting a string and not a buffer. ~Although buffers are being piped to it.~ <= not the case, I was using the API wrong so my transformer wasn't being called.

Wanted to give other folks a heads up. I'm assuming this issue is due to Node APIs changing.

Removing the `{objectMode: true}` option [on this line](https://github.com/mhart/kinesis/blob/master/index.js#L22)  caused the stream to receive a buffer. 

There are two ways to fix it in my (somewhat naive and hurried) opinion. 

1. don't pass that option to `stream.Duplex` or...
2. check for a buffer, if it's not a buffer, set `data = Buffer.from(data, encoding)`

If you're interested @mhart I can make a PR.

**Comment by twhid** [comment]
Following up..

For folks that are new to streams and maybe don't read [the docs](https://nodejs.org/api/stream.html) as closely as they should (like me), if you're getting a string from your source (e.g. [bunyan](https://github.com/trentm/node-bunyan)), then you need to transform the stream to a buffer (this kinesis module only works with buffers rn).

Here is a snippet that does the basics of adding a kinesis writeable stream to bunyan (tested in node v12.14.0):

```js
const { Transform } = require('stream');
const kinesis = require('kinesis');

const kinesisSink = kinesis.stream({ name: 'my.name', region: 'us-east-1' });

// bunyan passes a string to a writeable's write method, but kinesis only 
// works with buffers, so you need to transform the string to a buffer
const bunyanKinesis = new Transform({
    objectMode: true,
    transform(chunk, _, done) {
        done(null, Buffer.from(chunk));
    },
});

bunyanKinesis.pipe(kinesisSink);

const log = bunyan.createLogger({
    name: 'foo',
    streams: [{
        stream: bunyanKinesis,
        // etc
    }]
});

```

**Comment by mhart** [comment]
Yeah, this is shown in the README: https://github.com/mhart/kinesis#example

This module deliberately doesn't transform the data in case you want to stream the records somewhere else first.
