### ISSUE TITLE
Very weird error

### ISSUE THREAD

**Issue by warnero** [mhart/kinesis#8]
OK, been using this locally with no issues. Deployed it to our staging server with no issues (on Heroku). But tried to push up to our production server and we're getting this error:

ValidationException: 1 validation error detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=56817 cap=56817]' at 'data' failed to satisfy constraint: Member must have length less than or equal to 51200
2014-04-18T22:24:45.613695+00:00 app[web.1]:     at OverridenClientRequest.<anonymous> (/app/node_modules/kaster-mongoose/node_modules/kaster/node_modules/kinesis/index.js:283:30)

From what I can tell it's aws4 that's throwing this somewhere but I haven't got a clue what's going on. We have our aws credentials saved as config variables (same exact credentials work on staging just fine).

Hoping you'll have a clue what this might be.

**Comment by MagoMet** [comment]
So what is the solution to this?

**Comment by boris-lapouga** [comment]
+1. 
I have circa 6k records to push per every batch on my production and I get this error, beforehand we've been using putRecord which increased dramatically CPU usage, thought batch will solve the issue but then we hit this one.
